package com.mocmay.ai;
import android.app.*; import android.os.*; import android.content.*; import android.net.Uri; import android.view.*; import android.widget.*; import java.util.*;
public class MainActivity extends Activity {
 TextView chat,mode; EditText input; LocalAgent agent; ModelManager models; static final int PICK_FILE=42,PICK_MODEL=43;
 @Override public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);agent=new LocalAgent(this);models=new ModelManager(this);chat=findViewById(R.id.chat);mode=findViewById(R.id.mode);input=findViewById(R.id.input);findViewById(R.id.send).setOnClickListener(v->send());findViewById(R.id.scan).setOnClickListener(v->append("AI",agent.reply("/scan")));findViewById(R.id.settings).setOnClickListener(v->showMenu());findViewById(R.id.attach).setOnClickListener(v->pickFile());handleShare(getIntent());append("AI","Xin chào! Mộc Mây AI v20 • Offline-first • GGUF/llama.cpp-ready.");}
 void send(){String s=input.getText().toString().trim();if(s.isEmpty())return;append("Bạn",s);input.setText("");new Thread(()->{String a=agent.reply(s);runOnUiThread(()->append("AI",a));}).start();}
 void append(String w,String s){chat.append("\n"+w+": "+s+"\n");}
 void pickFile(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");startActivityForResult(i,PICK_FILE);}
 void pickModel(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/octet-stream");startActivityForResult(i,PICK_MODEL);}
 @Override protected void onActivityResult(int r,int code,Intent d){super.onActivityResult(r,code,d);if(code!=RESULT_OK||d==null||d.getData()==null)return;Uri u=d.getData();if(r==PICK_FILE)append("Hệ thống","Đã chọn: "+u);else if(r==PICK_MODEL){String name="model.gguf";try{android.database.Cursor c=getContentResolver().query(u,null,null,null,null);if(c!=null&&c.moveToFirst()){int x=c.getColumnIndex(android.provider.OpenableColumns.DISPLAY_NAME);if(x>=0)name=c.getString(x);}if(c!=null)c.close();models.importFromUri(getContentResolver(),u,name);append("Model","Đã import: "+name+"\nDùng /load "+name+" để nạp vào RAM.");}catch(Exception e){append("Model","Import thất bại: "+e.getMessage());}}}
 void handleShare(Intent i){if(i==null)return;if(Intent.ACTION_SEND.equals(i.getAction())){Uri u=i.getParcelableExtra(Intent.EXTRA_STREAM);if(u!=null)append("Share","Đã nhận file: "+u);String t=i.getStringExtra(Intent.EXTRA_TEXT);if(t!=null)input.setText(t);}else if(Intent.ACTION_SEND_MULTIPLE.equals(i.getAction()))append("Share","Đã nhận nhiều file.");}
 void showMenu(){new AlertDialog.Builder(this).setTitle("Mộc Mây AI v20").setItems(new String[]{"Import model GGUF","Danh sách model","Trạng thái","Hướng dẫn /help","Online connector"},(d,w)->{if(w==0)pickModel();else if(w==1)append("Model",agent.reply("/models"));else if(w==2)new AlertDialog.Builder(this).setTitle("Status").setMessage(agent.reply("/status")).setPositiveButton("OK",null).show();else if(w==3)append("AI",agent.reply("/help"));else new AlertDialog.Builder(this).setTitle("Online").setMessage("Tắt mặc định. Không nhúng API key vào APK.").setPositiveButton("OK",null).show();}).show();}
}
